version: '3.5'
services:
  server:
    image: gzseee/cve-search:latest
    environment:
      - REDIS_HOST=redis
      - MONGODB_HOST=mongo
      - MONGODB_DATABASE=cvesearch
      - MONGODB_USERNAME=cvesearch
      - MONGODB_PASSWORD=changeme
      - REDIS_PASSWORD=changeme
    ports:
      - 5000:5000
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=changeme
    ports:
      - '6379:6379'
    volumes:
      - '/mnt/cvesearch/redis:/bitnami/redis/data'
  mongo:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=cvesearch
      - MONGODB_USERNAME=cvesearch
      - MONGODB_PASSWORD=changeme
    volumes:
      - '/mnt/cvesearch/mongo:/bitnami'
